# Generated by Django 3.2 on 2024-04-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repair_cost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=20)),
                ('unit_laber_cost', models.FloatField()),
                ('material_cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Repair_man',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Repair_manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service_advisor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('user_password', models.CharField(max_length=20)),
                ('user_character', models.CharField(max_length=20, null=True)),
                ('user_discount', models.FloatField(null=True)),
                ('user_email', models.CharField(max_length=20, null=True)),
                ('user_phone', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('license_plate', models.CharField(max_length=10)),
                ('ident_number', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='User_Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amm.user')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amm.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Repair_order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=20)),
                ('work_time', models.DateTimeField()),
                ('repair_man_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amm.repair_man')),
            ],
        ),
        migrations.CreateModel(
            name='Repair_commission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wash', models.BooleanField()),
                ('material_cost', models.FloatField()),
                ('labor_cost', models.FloatField()),
                ('time', models.DateTimeField()),
                ('expected_delivery_time', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amm.vehicle')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amm.user')),
                ('service_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amm.service_advisor')),
            ],
        ),
    ]
